config/routes.rb
require 'sidekiq/web'
require "sidekiq/cron/web"

Rails.application.routes.draw do
  resources :docker_hub_registries
  resources :autobuilds
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  get '/oauth/github/apps', to: 'linked_apps#github_apps', as: 'linked_github_apps'
  get '/oauth/gitlab/apps', to: 'linked_apps#gitlab_apps', as: 'linked_gitlab_apps'
  delete '/oauth/github/apps/:id', to: 'linked_apps#github_delete', as: 'delete_linked_github_app'
  delete '/oauth/gitlab/apps/:id', to: 'linked_apps#gitlab_delete', as: 'delete_linked_gitlab_app'

  # Github Code Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # Gitlab Code Repos
  get '/linked_apps/gitlab/:id/repos', to: 'linked_apps#gitlab_repos_for_app'

  # Docker Registry Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # OAuth Callbacks
  get '/oauth/github/callback', to: 'linked_apps#github_success', as: 'github_oauth_callback'
  get '/oauth/gitlab/callback', to: 'linked_apps#gitlab_success', as: 'gitlab_oauth_callback'

  # Webhooks
  post '/github/webhooks/:id/', to: 'webhooks#github', as: 'github_webhook'
  post '/gitlab/webhooks/:id/', to: 'webhooks#gitlab', as: 'gitlab_webhook'

  get '/build_jobs', to: 'build_jobs#index', as: 'build_jobs'
  get '/build_jobs/:id/dockerfile', to: 'build_jobs#dockerfile', as: 'build_job_dockerfile'
  get '/build_jobs/:id/logs', to: 'build_jobs#logs', as: 'build_job_logs'

  root to: 'build_jobs#index'
  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/autobuild.rb
class Autobuild < ApplicationRecord
  belongs_to :user
  belongs_to :github_linked_app, optional: true
  belongs_to :gitlab_linked_app, optional: true
  has_and_belongs_to_many :docker_hub_registries
  has_one :github_repository
  has_one :gitlab_repository
  has_many :build_jobs
  # has_one :gitlab_repository

  # TODO: What other kind of validations do we need for different rule combinations?
  validates :name, presence: true
  validates :code_repo_name, presence: true, exclusion: { in: ["Select Github Repo"], message: "should be selected" }
  validates :code_repo_type, presence: true, exclusion: { in: ["Select Github Repo"], message: "should be selected" }
  validates :docker_hub_registries, length: { minimum: 1, maximum: 1, message: "can't be empty" }
  validate  :rules_cant_be_empty, :source_type_is_tag_or_branch,
            :source_is_valid, :docker_tag_is_valid, :dockerfile_is_valid,
            :build_context_is_valid, :at_least_one_linked_app

  after_create :create_repo_webhook
  before_destroy :remove_repo_webhook

  def rules_cant_be_empty
    rules.count == 0 ? errors.add(:rules, "can't be empty.") : nil
  end

  def source_type_is_tag_or_branch
    unless rules&.all? { |rule| ["tag", "branch"].include? rule.dig("source_type") }
      errors.add(:rules, "source type should be either tag or branch.")
    end
  end

  def source_is_valid
    if rules&.any? { |rule| rule.dig("source").blank? }
      errors.add(:rules, "source can't be empty.")
    end
  end

  def docker_tag_is_valid
    if rules&.any? { |rule| rule.dig("docker_tag").blank? }
      errors.add(:rules, "docker tag can't be empty.")
    end
  end

  def dockerfile_is_valid
    if rules&.any? { |rule| rule.dig("dockerfile").blank? }
      errors.add(:rules, "Dockerfile can't be empty.")
    end
  end

  def build_context_is_valid
    if rules&.any? { |rule| rule.dig("build_context").blank? }
      errors.add(:rules, "build context can't be empty.")
    end
  end

  def at_least_one_linked_app
    if gitlab_linked_app.blank? && github_linked_app.blank?
      errors.add(:code_repo, "configure at least one code repo for autobuild")
    end
  end

  def create_repo_webhook
    CreateRepoWebhookWorker.perform_async(self.id)
  end

  def remove_repo_webhook
    webhook_id = webhook_config.to_h.dig("id")
    linked_app_id = code_repo_type == 'github' ? github_linked_app.id : gitlab_linked_app.id
    RemoveRepoWebhookWorker.perform_async(code_repo_type, code_repo_name, webhook_id, linked_app_id)
  end
end

app/controllers/autobuilds_controller.rb
class AutobuildsController < ApplicationController
  before_action :set_autobuild, only: %i[ edit update destroy ]

  def index
    @autobuilds = current_user.autobuilds.paginate(page: params[:page], per_page: 10)
  end

  def new
    @autobuild = current_user.autobuilds.new
    @github_linked_apps = current_user.github_linked_apps
    @gitlab_linked_apps = current_user.gitlab_linked_apps
    @docker_hub_registries = current_user.docker_hub_registries
  end

  def edit
  end

  def create
    @github_linked_apps = current_user.github_linked_apps
    @docker_hub_registries = current_user.docker_hub_registries
    @autobuild = current_user.autobuilds.create({
      name: autobuild_params["name"],
      description: autobuild_params["description"],
      github_linked_app: current_user.github_linked_apps.where(id: autobuild_params["github_linked_app"]).first,
      gitlab_linked_app: current_user.gitlab_linked_apps.where(id: autobuild_params["gitlab_linked_app"]).first,
      docker_hub_registries: current_user.docker_hub_registries.where(id: autobuild_params["docker_registry"]).to_a,
      code_repo_name: autobuild_params["code_repo_name"],
      code_repo_type: autobuild_params["code_repo_type"],
      rules: autobuild_params["rules"]&.values.to_a.first(10), # TODO: Make this configurable,
      env_vars: autobuild_params["env_vars"]&.values.to_a.first(20) # TODO: Make this configurable,
    })
    if @autobuild.save
      redirect_to autobuilds_path, notice: "Autobuild was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @github_linked_apps = current_user.github_linked_apps
    @docker_hub_registries = current_user.docker_hub_registries
    if @autobuild.update({
      name: autobuild_params["name"],
      description: autobuild_params["description"],
      rules: autobuild_params["rules"]&.values.to_a.first(10), # TODO: Make this configurable
      env_vars: autobuild_params["env_vars"]&.values.to_a.first(20) # TODO: Make this configurable,
    })
      redirect_to autobuilds_path, notice: "Autobuild was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @autobuild.destroy
    redirect_to autobuilds_path, notice: "Autobuild was successfully destroyed."
  end

  private
    def set_autobuild
      @autobuild = current_user.autobuilds.find(params[:id])
    end

    def autobuild_params
      raw_params = params.require(:autobuild).permit(
        :name,
        :description,
        :docker_registry,
        :github_linked_app,
        :gitlab_linked_app,
        :code_repo_type,
        :code_repo_name,
        {
          env_vars: [
            :key,
            :value
          ]
        },
        {
          rules: [
            :source_type,
            :source,
            :docker_tag,
            :dockerfile,
            :build_context,
            :autobuild
          ]
        }
      )

      # autobuild checkboxes ar returned as "0" & "1"
      # instead of "false" & "true". So, let's cast it to boolean
      # TODO: Better way to do this?
      raw_params["rules"]&.values.to_a.each do |rule|
        rule["autobuild"] = ActiveModel::Type::Boolean.new.cast(rule["autobuild"])
      end

      raw_params
    end
end

app/helpers/autobuilds_helper.rb
module AutobuildsHelper
end

app/views/autobuilds/_form.html.erb
<div class="d-none d-flex flex-column min-vh-100 justify-content-center align-items-center" id="newAutobuildOverlay">
  <div class="text-white spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
  <span class="text-white mt-3">Fetching Code Repositories...</span>
</div>
<%= form_with(model: autobuild, class: "contents") do |form| %>
  <% if autobuild.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% autobuild.errors.each do |error| %>
        <span><%= error.full_message %></span><br />
      <% end %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, "Name", class: 'h5' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, "Description", class: 'h5' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <% if autobuild.new_record? %>
    <div class="row">
      <div class="col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuildRepoType" class="h5 form-label">Select Repository Type</label>
            <select name="autobuild[code_repo_type]" id="autobuild_code_repo_type" class="form-select">
              <option selected>Select Repository Type</option>
              <option value="github">Github</option>
              <option value="gitlab">Gitlab</option>
            </select>
          </div>
        </div>
      </div>
      <div id="autobuildGithubAppContainer" class="d-none col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuild_github_app" class="h5 form-label">Select Github Org</label>
            <select name="autobuild[github_linked_app]" id="autobuild_github_app" class="form-select">
              <option selected>Select Github Org</option>
              <%= @github_linked_apps.to_a.each do |app| %>
                <option value="<%= app.id %>"><%= app.username %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div id="autobuildGitlabAppContainer" class="d-none col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuild_gitlab_app" class="h5 form-label">Select Github Org</label>
            <select name="autobuild[gitlab_linked_app]" id="autobuild_gitlab_app" class="form-select">
              <option selected>Select Gitlab Org</option>
              <%= @gitlab_linked_apps.to_a.each do |app| %>
                <option value="<%= app.id %>"><%= app.username %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div id="codeRepoListContainer" class="d-none col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuild_code_repo_name" class="h5 form-label">Code Repo</label>
            <select name="autobuild[code_repo_name]" id="autobuild_code_repo_name" class="form-select">
              <option value="0" selected>Select Code Repo</option>
            </select>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="dockerRegistryTypeContainer" class="col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuild_docker_registry_type" class="h5 form-label">Docker Registry Type</label>
            <select id="autobuild_docker_registry_type" class="form-select">
              <option selected>Select Docker Registry Type</option>
              <option value="dockerhub">DockerHub</option>
              <!-- <option value="awsecr">AWS ECR</option> -->
            </select>
          </div>
        </div>
      </div>
      <div id="dockerRegistryListContainer" class="d-none col-lg-4">
        <div class="form-group mb-3">
          <div class="mb-3">
            <label for="autobuild_docker_registry" class="h5 form-label">Docker Registry</label>
            <select name="autobuild[docker_registry]" id="autobuild_docker_registry" class="form-select">
              <option selected>Select Docker Registry</option>
              <%= @docker_hub_registries.where(verification_status: 'complete').to_a.each do |reg| %>
                <option value="<%= reg.id %>"><%= reg.repo_name %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group mb-3">
          <label class="h5 form-label">Repository Name</label>
          <span readonly class="form-control"><%= autobuild.code_repo_name %></span>
          <small>You cannot change the Code Repo after creating an Autobuild</small>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group mb-3">
          <label class="h5 form-label">Docker Registry</label>
          <span readonly class="form-control"><%= autobuild.docker_hub_registries.first.try(:repo_name) %></span>
          <small>You cannot change the Docker Hub registry after creating an Autobuild</small>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <label for="autobuildRules" class="mb-0 h5 form-label">Build Rules <a id="addBuildRule" href="#"><i class="ms-2 fa fa-plus text-primary"></i></a></label>
      <small class="d-block">You can have up to 10 Build Rules per Autobuild</small>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
              <th>Source Type</th>
              <th>Source</th>
              <th>Docker Tag</th>
              <th>Dockerfile Name</th>
              <th>Build Context</th>
              <th>Autobuild</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id="buildRulesContainer">
            <% if action_name == "new" %>
              <!-- TODO: This should probably be a separate partial -->
              <tr>
                <!-- TODO: Add poppers with help info for each of this -->
                <td><%= form.select "rules[0][source_type]", [["Branch", "branch"], ["Tag", "tag"]], {}, { class: 'form-select'} %></td>
                <td><%= form.text_field "rules[0][source]", value: 'master', placeholder: 'master', class: 'form-control' %></td>
                <td><%= form.text_field "rules[0][docker_tag]", value: 'latest', placeholder: 'latest', class: 'form-control' %></td>
                <td><%= form.text_field "rules[0][dockerfile]", value: 'Dockerfile', placeholder: 'Dockerfile', class: 'form-control' %></td>
                <td><%= form.text_field "rules[0][build_context]", value: '/', placeholder: '/', class: 'form-control' %></td>
                <td><%= form.check_box "rules[0][autobuild]", checked: true, class: 'form-check-input align-middle' %></td>
                <td><%= link_to 'Delete', '#', class: 'deleteBuildRule btn btn-danger btn-sm' %></td>
              </tr>
            <% else %>
              <% autobuild.rules.to_a.each_with_index do |rule, i| %>
                <tr>
                  <td><%= form.select "rules[#{i}][source_type]", [["Branch", "branch"], ["Tag", "tag"]], { selected: rule.dig("source_type") }, { class: 'form-select'} %></td>
                  <td><%= form.text_field "rules[#{i}][source]", value: rule.dig("source"), placeholder: 'master', class: 'form-control' %></td>
                  <td><%= form.text_field "rules[#{i}][docker_tag]", value: rule.dig("docker_tag"), placeholder: 'latest', class: 'form-control' %></td>
                  <td><%= form.text_field "rules[#{i}][dockerfile]", value: rule.dig("dockerfile"), placeholder: 'Dockerfile', class: 'form-control' %></td>
                  <td><%= form.text_field "rules[#{i}][build_context]", value: rule.dig("build_context"), placeholder: '/', class: 'form-control' %></td>
                  <td><%= form.check_box "rules[#{i}][autobuild]", checked: rule.dig("autobuild"), class: 'form-check-input align-middle' %></td>
                  <td><%= link_to 'Delete', '#', class: 'deleteBuildRule btn btn-danger btn-sm' %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-lg-12">
      <div class="accordion" id="buildRuleExamples">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-coreui-toggle="collapse" data-coreui-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Build Rule Examples
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" data-coreui-parent="#buildRuleExamples">
            <div class="accordion-body">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Scenario</th>
                    <th scope="col">Source Type</th>
                    <th scope="col">Source</th>
                    <th scope="col">Docker Tag</th>
                    <th scope="col">Matches</th>
                    <th scope="col">Docker Tag Built</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Exact match</th>
                    <td>Branch</td>
                    <td>master</td>
                    <td>latest</td>
                    <td>master</td>
                    <td>latest</td>
                  </tr>
                  <tr>
                    <td>Match versions</th>
                    <td>Tag</td>
                    <td>/^[0-9.]+$/</td>
                    <td>release-{sourceref}</td>
                    <td>1.2.0</td>
                    <td>release-1.2.0</td>
                  </tr>
                  <tr>
                    <td>Trailing modifiers</th>
                    <td>Tag</td>
                    <td>/^[0-9.]+/</td>
                    <td>release-{sourceref}</td>
                    <td>1.2.0-rc</td>
                    <td>release-1.2.0-rc</td>
                  </tr>
                  <tr>
                    <td>Extract version number</td>
                    <td>Tag</td>
                    <td>/^v([0-9.]+)$/</td>
                    <td>version-{\1}</td>
                    <td>v1.2.3</td>
                    <td>version-1.2.3</td>
                  </tr>
                </tbody>
              </table>
              <small>Svennex supports the same configuration supported by Docker Hub for Build Rules.</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <label class="mb-0 h5 form-label">Environment Variables <a id="addEnvVars" href="#"><i class="ms-2 fa fa-plus text-primary" aria-hidden="true"></i></a></label>
      <small class="d-block">You can have up to 20 Environment Variables per Autobuild</small>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
              <th>Key</th>
              <th>Value</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id="envVarsContainer">
            <% if action_name == "new" %>
              <!-- TODO: This should probably be a separate partial -->
              <tr>
                <!-- TODO: Add poppers with help info for each of this -->
                <td><%= form.text_field "env_vars[0][key]", placeholder: 'DEBUG', class: 'form-control' %></td>
                <td><%= form.text_field "env_vars[0][value]", placeholder: 'true', class: 'form-control' %></td>
                <td><%= link_to 'Delete', '#', class: 'deleteBuildRule btn btn-danger btn-sm' %></td>
              </tr>
            <% else %>
              <% autobuild.env_vars.to_a.each_with_index do |env_var, i| %>
                <tr>
                  <td><%= form.text_field "env_vars[#{i}][key]", value: env_var.dig("key"), placeholder: 'DEBUG', class: 'form-control' %></td>
                  <td><%= form.text_field "env_vars[#{i}][value]", value: env_var.dig("value"), placeholder: 'true', class: 'form-control' %></td>
                  <td><%= link_to 'Delete', '#', class: 'deleteBuildRule btn btn-danger btn-sm' %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>

  <div class="inline">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>
<%= javascript_pack_tag 'autobuild_new.js' %>

app/views/autobuilds/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>Edit Autobuild</h3>
      </div>
      <div class="card-body">
        <%= render "form", autobuild: @autobuild %>
      </div>
    </div>
  </div>
</div>

app/views/autobuilds/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h2>Autobuilds</h2>
      </div>
      <div class="card-body">
        <!-- TODO: Show info message here asking user to create an Autobuild -->
        <% if current_user.autobuilds.empty? %>
        <% end %>
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @autobuilds.each do |autobuild| %>
              <tr>
                <td><%= autobuild.name %></td>
                <td><%= autobuild.description %></td>
                <td>
                  <%= link_to 'View/Edit', edit_autobuild_path(autobuild), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Delete', autobuild_path(autobuild), method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: "Are you sure?"} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Add Autobuild', new_autobuild_path, class: 'mb-3 btn btn-primary' %>
        <%= render partial: "partials/pagination", locals: { resources: @autobuilds, max_page: 10 } %>
      </div>
    </div>
  </div>
</div>

app/views/autobuilds/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>New Autobuild</h3>
      </div>
      <div class="card-body">
        <%= render "form", autobuild: @autobuild %>
      </div>
    </div>
  </div>
</div>