config/routes.rb
require 'sidekiq/web'
require "sidekiq/cron/web"

Rails.application.routes.draw do
  resources :docker_hub_registries
  resources :autobuilds
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  get '/oauth/github/apps', to: 'linked_apps#github_apps', as: 'linked_github_apps'
  get '/oauth/gitlab/apps', to: 'linked_apps#gitlab_apps', as: 'linked_gitlab_apps'
  delete '/oauth/github/apps/:id', to: 'linked_apps#github_delete', as: 'delete_linked_github_app'
  delete '/oauth/gitlab/apps/:id', to: 'linked_apps#gitlab_delete', as: 'delete_linked_gitlab_app'

  # Github Code Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # Gitlab Code Repos
  get '/linked_apps/gitlab/:id/repos', to: 'linked_apps#gitlab_repos_for_app'

  # Docker Registry Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # OAuth Callbacks
  get '/oauth/github/callback', to: 'linked_apps#github_success', as: 'github_oauth_callback'
  get '/oauth/gitlab/callback', to: 'linked_apps#gitlab_success', as: 'gitlab_oauth_callback'

  # Webhooks
  post '/github/webhooks/:id/', to: 'webhooks#github', as: 'github_webhook'
  post '/gitlab/webhooks/:id/', to: 'webhooks#gitlab', as: 'gitlab_webhook'

  get '/build_jobs', to: 'build_jobs#index', as: 'build_jobs'
  get '/build_jobs/:id/dockerfile', to: 'build_jobs#dockerfile', as: 'build_job_dockerfile'
  get '/build_jobs/:id/logs', to: 'build_jobs#logs', as: 'build_job_logs'

  root to: 'build_jobs#index'
  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/docker_hub_registry.rb
class DockerHubRegistry < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :autobuilds

  validates :name, presence: true
  validates :username, presence: true
  validates :repo_name, presence: true
  validates :access_token, presence: true

  after_create :verify_registry_access

  def verify_registry_access
    VerifyDockerHubRegistryAccessWorker.perform_async(id)
  end
end

app/controllers/docker_hub_registries_controller.rb
class DockerHubRegistriesController < ApplicationController
  before_action :set_docker_hub_registry, only: %i[ edit update destroy ]

  def index
    @docker_hub_registries = current_user.docker_hub_registries.paginate(page: params[:page], per_page: 10)
  end

  def new
    @docker_hub_registry = current_user.docker_hub_registries.new
  end

  def edit
  end

  def create
    @docker_hub_registry = current_user.docker_hub_registries.new(docker_hub_registry_params)
    if @docker_hub_registry.save
      redirect_to docker_hub_registries_path, notice: "Docker hub registry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @docker_hub_registry.update(docker_hub_registry_params)
      redirect_to docker_hub_registries_path, notice: "Docker hub registry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @docker_hub_registry.destroy
    redirect_to docker_hub_registries_url, notice: "Docker hub registry was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docker_hub_registry
      @docker_hub_registry = current_user.docker_hub_registries.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def docker_hub_registry_params
      params.require(:docker_hub_registry).permit(
        :name,
        :description,
        :username,
        :repo_name,
        :access_token
      )
    end
end

app/helpers/docker_hub_registries_helper.rb
module DockerHubRegistriesHelper
end

app/views/docker_hub_registries/_form.html.erb
<%= form_with(model: docker_hub_registry, class: "contents") do |form| %>
  <% if docker_hub_registry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% docker_hub_registry.errors.each do |error| %>
        <span><%= error.full_message %></span><br />
      <% end %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, "Name", class: 'h5' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, "Description", class: 'h5' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :username, "Dockerhub Username", class: 'h5' %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :username, "Dockerhub Repository Name", class: 'h5' %>
    <%= form.text_field :repo_name, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :access_token, "Access Token", class: 'h5' %>
    <%= form.text_field :access_token, type: :password, class: 'form-control' %>
  </div>

  <div class="inline">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/docker_hub_registries/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>Edit Docker Hub Registry</h3>
      </div>
      <div class="card-body">
        <%= render "form", docker_hub_registry: @docker_hub_registry %>
      </div>
    </div>
  </div>
</div>

app/views/docker_hub_registries/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h2>Docker Hub Registries</h2>
      </div>
      <div class="card-body">
        <!-- TODO: Show info message here asking user to create an Autobuild -->
        <% if current_user.docker_hub_registries.empty? %>
        <% end %>
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Verification</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @docker_hub_registries.each do |registry| %>
              <tr>
                <td><%= registry.name %></td>
                <td><%= registry.description %></td>
                <td><%= registry.verification_status.titleize %></td>
                <td>
                  <%= link_to 'View/Edit', edit_docker_hub_registry_path(registry), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Delete', docker_hub_registry_path(registry), method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: "Are you sure?"} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Add Docker Hub Registry', new_docker_hub_registry_path, class: 'mb-3 btn btn-primary' %>
        <%= render partial: "partials/pagination", locals: { resources: @docker_hub_registries, max_page: 10 } %>
      </div>
    </div>
  </div>
</div>

app/views/docker_hub_registries/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>New Docker Hub Registry</h3>
      </div>
      <div class="card-body">
        <%= render 'form', docker_hub_registry: @docker_hub_registry %>
      </div>
    </div>
  </div>
</div>

app/views/docker_hub_registries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_docker_hub_registry_path(@docker_hub_registry) %> |
<%= link_to 'Back', docker_hub_registries_path %>