config/routes.rb
require 'sidekiq/web'
require "sidekiq/cron/web"

Rails.application.routes.draw do
  resources :docker_hub_registries
  resources :autobuilds
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  get '/oauth/github/apps', to: 'linked_apps#github_apps', as: 'linked_github_apps'
  get '/oauth/gitlab/apps', to: 'linked_apps#gitlab_apps', as: 'linked_gitlab_apps'
  delete '/oauth/github/apps/:id', to: 'linked_apps#github_delete', as: 'delete_linked_github_app'
  delete '/oauth/gitlab/apps/:id', to: 'linked_apps#gitlab_delete', as: 'delete_linked_gitlab_app'

  # Github Code Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # Gitlab Code Repos
  get '/linked_apps/gitlab/:id/repos', to: 'linked_apps#gitlab_repos_for_app'

  # Docker Registry Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # OAuth Callbacks
  get '/oauth/github/callback', to: 'linked_apps#github_success', as: 'github_oauth_callback'
  get '/oauth/gitlab/callback', to: 'linked_apps#gitlab_success', as: 'gitlab_oauth_callback'

  # Webhooks
  post '/github/webhooks/:id/', to: 'webhooks#github', as: 'github_webhook'
  post '/gitlab/webhooks/:id/', to: 'webhooks#gitlab', as: 'gitlab_webhook'

  get '/build_jobs', to: 'build_jobs#index', as: 'build_jobs'
  get '/build_jobs/:id/dockerfile', to: 'build_jobs#dockerfile', as: 'build_job_dockerfile'
  get '/build_jobs/:id/logs', to: 'build_jobs#logs', as: 'build_job_logs'

  root to: 'build_jobs#index'
  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/linked_apps_controller.rb
class LinkedAppsController < ApplicationController
  include LinkedAppsHelper

  def github_apps
    # Refers to state described here
    # https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps
    @github_state = SecureRandom.hex(20)
    APP_REDIS_POOL.with do |client|
      client.set(@github_state, current_user.id, ex: 86400)
    end
    @github_url = "https://github.com/login/oauth/authorize?client_id=#{ENV['GITHUB_OAUTH_CLIENT_ID']}&scope=repo&state=#{@github_state}"

    @github_apps = current_user.github_linked_apps.paginate(page: params[:page], per_page: 10)
  end

  def gitlab_apps
    @gitlab_state = SecureRandom.hex(20)
    APP_REDIS_POOL.with do |client|
      client.set(@gitlab_state, current_user.id, ex: 86400)
    end

    @gitlab_url = "https://gitlab.com/oauth/authorize?client_id=#{ENV['GITLAB_OAUTH_CLIENT_ID']}&redirect_uri=#{ENV['GITLAB_OAUTH_REDIRECT_URL']}&response_type=code&state=#{@gitlab_state}&scope=read_repository read_user read_api api"
    @gitlab_apps = current_user.gitlab_linked_apps.paginate(page: params[:page], per_page: 10)
  end

  def github_delete
    github_app = current_user.github_linked_apps.find(params[:id])
    if github_app
      github_app.destroy!
      redirect_to linked_github_apps_path
    end
  end

  def gitlab_delete
    gitlab_app = current_user.gitlab_linked_apps.find(params[:id])
    if gitlab_app
      gitlab_app.destroy!
      redirect_to linked_gitlab_apps_path
    end
  end

  def github_repos_for_app
    # TODO: Error handling
    linked_app = current_user.github_linked_apps.find(params[:id])
    access_token = linked_app.access_token

    # TODO: Should a single instance of client be initialized and used everywhere?
    client = Octokit::Client.new(access_token: access_token)
    client.auto_paginate = true

    # Let's not bombard Github API if a client goes rogue
    repo_names = Rails.cache.fetch("#{session.id}/linked_apps/github/#{linked_app.id}/repos", expires_in: 1.minute) do
      repos = client.repos
      repos.select { |r| r[:owner][:login] == linked_app.username }.pluck(:full_name)
    end
    render json: repo_names
  end

  def gitlab_repos_for_app
    # TODO: Error handling
    linked_app = current_user.gitlab_linked_apps.find(params[:id])
    access_token = linked_app.access_token

    # Let's not bombard Gitlab API if a client goes rogue
    project_names = Rails.cache.fetch("#{session.id}/linked_apps/gitlab/#{linked_app.id}/repos", expires_in: 1.minute) do
      # TODO: Should a single instance of client be initialized and used everywhere?
      Gitlab.endpoint = "https://gitlab.com/api/v4"
      Gitlab.private_token = access_token

      begin
        user = Gitlab.user
      rescue Gitlab::Error::Unauthorized => e
        refresh_gitlab_access_token(linked_app)
        access_token = linked_app.access_token
        Gitlab.private_token = access_token
        user = Gitlab.user
      end
      projects = Gitlab.get("/users/#{user.id}/projects").auto_paginate
      projects.map(&:path_with_namespace)
    end
    render json: project_names
  end

  def github_success
    state = params[:state]
    code = params[:code]
    @success = true

    user_id = APP_REDIS_POOL.with do |client|
      client.get(state)
    end

    # If we can find the state in our cache
    if user_id
      # Push getting access token to the background
      AddNewGithubOrgWorker.perform_async(user_id, code)
    else
      @success = false
    end
  end

  def gitlab_success
    state = params[:state]
    code = params[:code]
    @success = true

    user_id = APP_REDIS_POOL.with do |client|
      client.get(state)
    end

    # If we can find the state in our cache
    if user_id
      # Push getting access token to the background
      AddNewGitlabOrgWorker.perform_async(user_id, code)
    else
      @success = false
    end
  end
end

app/helpers/linked_apps_helper.rb
module LinkedAppsHelper
  def refresh_gitlab_access_token(linked_app)
    refresh_token = linked_app.refresh_token
    _response = HTTParty.post(
      'https://gitlab.com/oauth/token',
      body: {
        client_id: ENV['GITLAB_OAUTH_CLIENT_ID'],
        client_secret: ENV['GITLAB_OAUTH_CLIENT_SECRET'],
        refresh_token: refresh_token,
        grant_type: 'refresh_token',
        redirect_uri: ENV['GITLAB_OAUTH_REDIRECT_URL']
      }.to_json,
      headers: { 'Content-Type' => 'application/json' }
    )

    # TODO: Else?
    if _response.code == 200
      response = JSON.parse _response.body
      access_token = response["access_token"]
      refresh_token = response["refresh_token"]

      linked_app.update({
        refresh_token: refresh_token,
        access_token: access_token
      })
    end
  end
end

app/views/linked_apps/github_apps.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>Github Organizations</h3>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th>Username</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @github_apps.each do |app| %>
              <tr>
                <td><%= app.username %></td>
                <td>
                  <%= link_to 'Delete', delete_linked_github_app_path(app), method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: "Are you sure?"} %>
                  <!-- TODO: Add more details here explaining that autobuilds will stop working -->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- TODO: Pagination here -->
        <a href="<%= @github_url %>" class="mb-3 btn btn-primary">Link a new Organization</a>
        <%= render partial: "partials/pagination", locals: { resources: @github_apps, max_page: 10 } %>
      </div>
    </div>
  </div>
</div>

app/views/linked_apps/github_success.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Success!</h4>
  <p>Github has been successfully linked to Svennex. You can now configure builds for repositories of this Github Organization.</p>
</div>

app/views/linked_apps/gitlab_apps.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3>Gitlab Organizations</h3>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th>Username</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @gitlab_apps.each do |app| %>
              <tr>
                <td><%= app.username %></td>
                <td>
                  <%= link_to 'Delete', delete_linked_gitlab_app_path(app), method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: "Are you sure?"} %>
                  <!-- TODO: Add more details here explaining that autobuilds will stop working -->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- TODO: Pagination here -->
        <a href="<%= @gitlab_url %>" class="mb-3 btn btn-primary">Link a new Organization</a>
        <%= render partial: "partials/pagination", locals: { resources: @gitlab_apps, max_page: 10 } %>
      </div>
    </div>
  </div>
</div>

app/views/linked_apps/gitlab_success.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Success!</h4>
  <p>Gitlab has been successfully linked to Svennex. You can now configure builds for repositories of this Gitlab Organization.</p>
</div>