config/routes.rb
require 'sidekiq/web'
require "sidekiq/cron/web"

Rails.application.routes.draw do
  resources :docker_hub_registries
  resources :autobuilds
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  get '/oauth/github/apps', to: 'linked_apps#github_apps', as: 'linked_github_apps'
  get '/oauth/gitlab/apps', to: 'linked_apps#gitlab_apps', as: 'linked_gitlab_apps'
  delete '/oauth/github/apps/:id', to: 'linked_apps#github_delete', as: 'delete_linked_github_app'
  delete '/oauth/gitlab/apps/:id', to: 'linked_apps#gitlab_delete', as: 'delete_linked_gitlab_app'

  # Github Code Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # Gitlab Code Repos
  get '/linked_apps/gitlab/:id/repos', to: 'linked_apps#gitlab_repos_for_app'

  # Docker Registry Repos
  get '/linked_apps/github/:id/repos', to: 'linked_apps#github_repos_for_app'

  # OAuth Callbacks
  get '/oauth/github/callback', to: 'linked_apps#github_success', as: 'github_oauth_callback'
  get '/oauth/gitlab/callback', to: 'linked_apps#gitlab_success', as: 'gitlab_oauth_callback'

  # Webhooks
  post '/github/webhooks/:id/', to: 'webhooks#github', as: 'github_webhook'
  post '/gitlab/webhooks/:id/', to: 'webhooks#gitlab', as: 'gitlab_webhook'

  get '/build_jobs', to: 'build_jobs#index', as: 'build_jobs'
  get '/build_jobs/:id/dockerfile', to: 'build_jobs#dockerfile', as: 'build_job_dockerfile'
  get '/build_jobs/:id/logs', to: 'build_jobs#logs', as: 'build_job_logs'

  root to: 'build_jobs#index'
  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/build_job.rb
class BuildJob < ApplicationRecord
  belongs_to :autobuild
end

app/controllers/build_jobs_controller.rb
class BuildJobsController < ApplicationController
  def index
    @build_jobs = current_user.build_jobs.paginate(page: params[:page], per_page: 10)
    @build_job_count = current_user.build_jobs.count
  end

  def dockerfile
    @build_job = current_user.build_jobs.find(params[:id])
    if @build_job.dockerfile_path
      @dockerfile_contents = File.read(@build_job.dockerfile_path)
    else
      @dockerfile_contents = "Dockerfile Unavailable"
    end
  end

  def logs
    @build_job = current_user.build_jobs.find(params[:id])
    if @build_job.build_logs_path
      @build_logs = File.read(@build_job.build_logs_path)
    else
      @build_logs = "Build Logs Unavailable"
    end
  end
end

app/views/build_jobs/dockerfile.html.erb
<div class="card">
  <div class="card-header">
    <h3>Dockerfile</h3>
  </div>
  <div class="text-white bg-dark card-body"><pre><code>
<%= @dockerfile_contents %></code></pre>
  </div>
</div>

app/views/build_jobs/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h2 class="mb-0">Build Jobs</h2>
        <!-- TODO: Make this configurable -->
        <small>Jobs older than 30 days are automatically removed.</small>
      </div>
      <div class="card-body">
        <% if @build_job_count == 0 %>
          <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">No Build Jobs!</h4>
            <p>You seem to not have any build jobs yet. Configure Autobuild and push your changes to generate a build job.</p>
          </div>
        <% else %>
          <table class="table table-striped table-hover table-bordered">
            <thead>
              <tr>
                <th>Created At</th>
                <th>Status</th>
                <th>Dockerfile</th>
                <th>Logs</th>
                <th>Size(MB)</th>
                <th>Commit</th>
                <th>Image URI</th>
                <th>Source Repo</th>
                <th>Duration(seconds)</th>
              </tr>
            </thead>
            <tbody>
              <% @build_jobs.each do |job| %>
                <tr>
                  <td><%= time_ago_in_words(job.created_at) + " ago" %></td>
                  <td><%= job.status.to_s.titleize %></td>
                  <td><%= link_to 'Dockerfile', build_job_dockerfile_path(job.id) %></td>
                  <td><%= link_to 'Logs', build_job_logs_path(job.id) %></td>
                  <th><%= (job.image_size.to_i/1000000.0).round(2) %></th>
                  <td><%= job.commit_sha.first(8) %></td>
                  <!-- TODO: Convert these to an actual links -->
                  <td><%= job.image_uri %></td>
                  <td><%= job.source_repo %></td>
                  <td><%= job.complete ? job.duration : '-' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
        <%= render partial: "partials/pagination", locals: { resources: @build_jobs, max_page: 10 } %>
      </div>
    </div>
  </div>
</div>

app/views/build_jobs/logs.html.erb
<div class="card">
  <div class="card-header">
    <h3>Build Logs</h3>
  </div>
  <div class="text-white bg-dark card-body"><pre><code>
<%= @build_logs %></code></pre>
  </div>
</div>